# Noor ul Huda Rasool




# PIAIC157843


# Course AI


# Batch 35

In [17]:
import numpy as np
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [18]:
import numpy as np
arr2 = np.array([[1,2],[5,8]])
arr2

array([[1, 2],
       [5, 8]])

In [23]:
import numpy as np
arr3= np.eye(5)
arr3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
import numpy as np
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
import numpy as np
arr5=np.array([1,2,3,4],dtype ='double')
arr5.dtype

dtype('float64')

In [31]:
import numpy as np
arr6 =np.array([1,2,3],dtype=int)
arr6.dtype

dtype('int32')

In [56]:
import numpy as np
arr7 = np.arange(10,3*3*3-1).reshape(2,2,2,2)
print(arr7)
print('---------')
print(arr7[[1,0]])
print('---------')
print(arr7[:,::-1,:])

[[[[10 11]
   [12 13]]

  [[14 15]
   [16 17]]]


 [[[18 19]
   [20 21]]

  [[22 23]
   [24 25]]]]
---------
[[[[18 19]
   [20 21]]

  [[22 23]
   [24 25]]]


 [[[10 11]
   [12 13]]

  [[14 15]
   [16 17]]]]
---------
[[[[10 11]
   [12 13]]]


 [[[18 19]
   [20 21]]]]


In [67]:
import numpy as np
arr8 = np.array(["Qadir","Hunzala","Ali"])
data = np.random.randn(10,2)#rows - columns
print(arr8,data,sep="\n")
arr8 == "Ali"


['Qadir' 'Hunzala' 'Ali']
[[ 0.05980109 -0.12818844]
 [ 1.2088216  -0.72527653]
 [ 0.76459031  0.82181867]
 [ 0.13785471 -0.53647864]
 [ 0.52171677  0.70869491]
 [-1.25226657  1.55279014]
 [-0.01357084 -0.37694702]
 [-0.59212702 -0.20527064]
 [-1.35854572  0.22510547]
 [ 0.00308249  0.36887546]]


array([False, False,  True])

In [93]:
import numpy as np
arr9 = 1,2,3
arr9 = np.arange(2*2*4).reshape(2,2,4)
print(arr9) 
arr9.T



[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [98]:
import numpy as np
ar10= np.arange(3*2).reshape((3,2))
print(ar10,"-----",sep="\n")
ar10.transpose(1,0)

[[0 1]
 [2 3]
 [4 5]]
-----


array([[0, 2, 4],
       [1, 3, 5]])

In [106]:
import numpy as np
ar11= np.arange(3*2).reshape(3,2)
print(ar11)
ar11.swapaxes(1,0)


[[0 1]
 [2 3]
 [4 5]]


array([[0, 2, 4],
       [1, 3, 5]])

In [108]:
import numpy as np
ar12=np.array([1,2,3,-4,5])
np.abs(ar12)

array([1, 2, 3, 4, 5])

In [111]:
import numpy as np
ar13=np.array([1,2,3,-4,5])
np.fabs(ar13)

array([1., 2., 3., 4., 5.])

In [115]:
import numpy as np
ar14 =np.array([1,20,3,-3,5,6])
np.square(ar14)

array([  1, 400,   9,   9,  25,  36], dtype=int32)

In [116]:
import numpy as np
ar15=np.array([1,20,3,-3,5,6])
np.exp(ar15)

array([2.71828183e+00, 4.85165195e+08, 2.00855369e+01, 4.97870684e-02,
       1.48413159e+02, 4.03428793e+02])

In [117]:
import numpy as np
np.isnan(np.nan)

True

In [122]:
import numpy as np
a17 = np.array([1,2,5,3,4,9])
a18= np.array([1,2,9,8,7,5])
np.maximum(a17,a18)

array([1, 2, 9, 8, 7, 9])

In [123]:
import numpy as np
a17 = np.array([1,2,5,3,4,9])
a18= np.array([1,2,9,8,7,5])
np.fmax(a17,a18)

array([1, 2, 9, 8, 7, 9])

In [131]:
import numpy as np
a19 = np.arange(2)
a19

array([0, 1])

In [136]:
import numpy as np
a19 = np.arange(3)
a20= np.meshgrid(a19,a19)
a20

[array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])]

In [138]:
import numpy as np
a21=np.arange(4*3)
a22= np.where(a21%3 == 0,"divisible by 3",'not divivsble by 3')
a22

array(['divisible by 3', 'not divivsble by 3', 'not divivsble by 3',
       'divisible by 3', 'not divivsble by 3', 'not divivsble by 3',
       'divisible by 3', 'not divivsble by 3', 'not divivsble by 3',
       'divisible by 3', 'not divivsble by 3', 'not divivsble by 3'],
      dtype='<U18')

In [140]:
import numpy as np
a23=np.arange(6)
a24=np.sum(a23)
a24

15

In [156]:
import numpy as np
a25=np.arange(16).reshape(4,4)

a26=np.sum(a25,axis=0)


a27=np.sum(a25,axis=1)
print(a25,a26,a27,sep ="------")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]------[24 28 32 36]------[ 6 22 38 54]


In [158]:
import numpy as np
a28=np.arange(4).reshape(1,4)
a28+5

array([[5, 6, 7, 8]])

In [161]:
import numpy as np
a29=np.arange(5*5).reshape(5,5)
a30=np.full_like(a29,5)
print(a29,a30,sep="-----")
a29+a30

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]-----[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

# stacking 

In [166]:
import numpy as np
a31=np.random.randint(1,10,size=10)
print(a31)
a=a31+5
print(len(a31),len(a))

[4 7 8 9 2 6 7 8 9 5]
10 10


In [174]:
import numpy as np
a32=np.random.randint(1,10,size=10)
a=a32+5
a33=np.stack((a32,a),axis=0)
print(a32,a33,sep="----")


[7 5 2 2 2 7 1 4 6 4]----[[ 7  5  2  2  2  7  1  4  6  4]
 [12 10  7  7  7 12  6  9 11  9]]


2

In [185]:
import numpy as np
a34=np.random.randint(1,10,size=10)
a35 = np.vstack(a34)
a35

array([[3],
       [9],
       [1],
       [2],
       [1],
       [2],
       [6],
       [4],
       [5],
       [3]])

In [ ]:
import numpy as np